### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by joker2013** [S4kur4/AutoDeployCuckoo#1]
https://csedurs-my.sharepoint.com/:u:/g/personal/s4kur4_casc_ren/EZqKiQg-pu9Lr5EioAnNqPUBgGB0Ohl6ogOZIclQ2cAtjg?e=v61KA3

**Comment by S4kur4** [comment]
> https://csedurs-my.sharepoint.com/:u:/g/personal/s4kur4_casc_ren/EZqKiQg-pu9Lr5EioAnNqPUBgGB0Ohl6ogOZIclQ2cAtjg?e=v61KA3

Onedrive sharing link expired, [try this](https://csedurs-my.sharepoint.com/:u:/g/personal/s4kur4_casc_ren/EZqKiQg-pu9Lr5EioAnNqPUBgGB0Ohl6ogOZIclQ2cAtjg?e=bMysBa).
