### ISSUE TITLE
Cuckoo ready.

### ISSUE THREAD

**Issue by Irigoshito** [S4kur4/AutoDeployCuckoo#11]
Hi S4kur4

Several changes were made to the script which resulted in a successful operation so that it works correctly and without errors.

I attach the changes.

<img width="416" alt="cambios20210916" src="https://user-images.githubusercontent.com/26231259/133725512-05b09128-00fa-4917-a346-370835d0124c.png">

'''''''''''''''''''''''''''''''''''''INICIO'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

# Install Python dependencies
sudo pip install -U sqlalchemy==1.3.3 dpkt==1.8.7 jinja2==2.9.6 pymongo==3.0.3 bottle yara-python==3.6.3 requests==2.13.0 python-dateutil==2.4.2 chardet==2.3.0 psycopg2 pycrypto pydeep distorm3 weasyprint==0.36 m2crypto openpyxl ujson pycrypto pytz

	# Se debe ejecutar por separado estos comandos Andres Reyes / Fabian Orosco
	#Inicio de los cambios

	#Instalación 2021-09-16
	sudo pip install -U pyOpenSSL
	# Install pefile library 2021-09-15
	sudo apt-get install python-pefile
	# Instalar librerias setuptools
	sudo pip install -U pip setuptools
        # Instalar la version del cuckoo 2-0.7
	sudo pip install -U cuckoo==2.0.7

        #Fin de los cambios y se continua normalmente.

	# Reinstall werkzeug
	sudo pip uninstall --yes werkzeug && sudo pip install werkzeug==0.16.1

Ubuntu version: 18.04.6 LTS Bionic Beaver.

Atentamente,
Fabian Orosco y Andres Reyes.
Ecuador - Quito

**Comment by S4kur4** [comment]
> Hi S4kur4
> 
> Several changes were made to the script which resulted in a successful operation so that it works correctly and without errors.
> 
> I attach the changes.
> 
> <img alt="cambios20210916" width="416" src="https://user-images.githubusercontent.com/26231259/133725512-05b09128-00fa-4917-a346-370835d0124c.png">
> 
> '''''''''''''''''''''''''''''''''''''INICIO'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> 
> # Install Python dependencies
> sudo pip install -U sqlalchemy==1.3.3 dpkt==1.8.7 jinja2==2.9.6 pymongo==3.0.3 bottle yara-python==3.6.3 requests==2.13.0 python-dateutil==2.4.2 chardet==2.3.0 psycopg2 pycrypto pydeep distorm3 weasyprint==0.36 m2crypto openpyxl ujson pycrypto pytz
> 
> ```
> # Se debe ejecutar por separado estos comandos Andres Reyes / Fabian Orosco
> #Inicio de los cambios
> 
> #Instalación 2021-09-16
> sudo pip install -U pyOpenSSL
> # Install pefile library 2021-09-15
> sudo apt-get install python-pefile
> # Instalar librerias setuptools
> sudo pip install -U pip setuptools
>     # Instalar la version del cuckoo 2-0.7
> sudo pip install -U cuckoo==2.0.7
> 
>     #Fin de los cambios y se continua normalmente.
> 
> # Reinstall werkzeug
> sudo pip uninstall --yes werkzeug && sudo pip install werkzeug==0.16.1
> ```
> 
> Ubuntu version: 18.04.6 LTS Bionic Beaver.
> 
> Atentamente,
> Fabian Orosco y Andres Reyes.
> Ecuador - Quito

Hey bro, very appreciate  this and I will make a script change after testing in my free time. Thanks a lot.

**Comment by S4kur4** [comment]
A new script has been released. Many thanks.
