### ISSUE TITLE
Step 2 Failure in install.sh

### ISSUE THREAD

**Issue by inegmdev** [S4kur4/AutoDeployCuckoo#15]
Hello,
First of all, thanks a lot for your effort to make such a great script to install Cuckoo.

For the context of the issue, here's my setup:
```
re@re:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

It's a fresh install of Ubuntu under a VirtualBox, in the log you will find that I did the following:
* apt update
* Use the script directly

## Expected
That the script success

## Actual
The script failed in step #2

Could you please help me?
Thanks a lot in advance.
_____________________________________
[install_sh_log.txt](https://github.com/S4kur4/AutoDeployCuckoo/files/9006171/install_sh_log.txt)

**Comment by inegmdev** [comment]
It seems that it's failing in `downloadAgent` due to depricated crypto package in python 2.

```
function downloadAgent() {
	# Agent.ova is a Windows7 (x86) virtual machine and used to be an Cuckoo agent
	url="https://drive.google.com/u/0/uc?id=1uGxNwvSuSIhokeuX9N61D8VtyFDoK0-2&export=download"
	# Download from google drive
	gdown --speed=50MB $url -O ~/Downloads/Agent.ova
}
```

I will work around this by downloading it manually.

**Comment by S4kur4** [comment]
@i-negm Sorry for my delay reply due to less spare time during my working days, let me verify the issue this weekend. Thanks!

**Comment by S4kur4** [comment]
Hey @i-negm I have released a new version and resolved the `gdown` tool error through modify the procedure logic. This issue seems caused by old `gdown` and its dependencies. Now `gdown` has been set to the latest version `4.5.1` and it works normally after my test. Appreciate if you also make a test, thanks!

**Comment by inegmdev** [comment]
Works like a charm!
Thanks for your efforts and time.
![image](https://user-images.githubusercontent.com/8951296/177678929-af60928d-c2bc-4603-868b-a84e66853d91.png)
