### ISSUE TITLE
Thank you for this script...I wanted to inform you of a slight issue

### ISSUE THREAD

**Issue by Magerly666** [S4kur4/AutoDeployCuckoo#18]
Hi!  Your script is excellent!  Thank you for taking the time to put it together.

One issue I ran into is with the function DownloadAgent.  If you do not have pip installed, then it won't install gdown.  May I suggest you move the function to after the function call of "installCuckooDependencies"...that way pip gets installed and then you download the Agent.ova.

Thanks!

**Comment by S4kur4** [comment]
It sounds make sense. I will do that this weekend in my spare time. Thanks for your advise!
