### ISSUE TITLE
Problem download Agent.ova

### ISSUE THREAD

**Issue by VenturiniGiacomo** [S4kur4/AutoDeployCuckoo#5]
Hi!

when I try to log in to dowload agent.ova i take this message: Cannot find "account@domain.com" in the csedurs-my.sharepoint.com directory. Please try again later. In the meantime, an attempt will be made to automatically resolve the problem.

**Comment by S4kur4** [comment]
Hey, I have changed the stored place for Agent.ova to Google Drive, see [issue 6](https://github.com/S4kur4/AutoDeployCuckoo/issues/6)
