### ISSUE TITLE
cuckoo1 not ready yet

### ISSUE THREAD

**Issue by pietrogu** [S4kur4/AutoDeployCuckoo#7]
Hi,

I installed cuckoo following the guide in an ubuntu server, but when i start the analysis i have a lot of this error:

2021-04-14 17:46:31,552 [cuckoo.core.guest] DEBUG: cuckoo2: not ready yet

and in cuckoo this is the message:

**_It appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to the connect to the Guest or the other way around (i.e., Guest wasn't able to contact the Cuckoo Host). There could be a few reasons for this:_**
- **_The IP address of the VM has been configured incorrectly. Please verify that the VM has a static IP address, that it matches the one in the Cuckoo configuration, and that the configured network interface exists and is up. Also, in case of VirtualBox, did you configure the network interface to be a "Host-Only interface"?_**
-  **_Please check that there are no firewalls in-place that hinder the communication between your Host and Guest_**

Anyone has already encountered this error?

Thanks,
Pietro

**Comment by pietrogu** [comment]
Solved, the actual IP of the VM was wrong

**Comment by prerna-pragati** [comment]
Hi what changes you made to solve this issue. Can you please mention.I am encountering the same issue.
