### ISSUE TITLE
Errores 

### ISSUE THREAD

**Issue by Irigoshito** [S4kur4/AutoDeployCuckoo#9]
Dispongo de la versión Ubuntu 18.04.6 LTS y codename bionic.

Queria consultarte si sabes a que se da este problema.

![image](https://user-images.githubusercontent.com/26231259/133373001-845ba497-ffc3-41cc-9d31-39e6d0155a39.png)
[Error cuckoo.docx](https://github.com/S4kur4/AutoDeployCuckoo/files/7166848/Error.cuckoo.docx)

Gracias.
Fabian ORosco

**Comment by S4kur4** [comment]
Have replied your email.
